### ISSUE TITLE
Error getting all countries

### ISSUE THREAD

**Issue by j-mary** [paulpascal/country_state_city#2]
**Describe the bug**
Cannot get Country data

**To Reproduce**
1. call the getAllCountries() function
2. See error

**Expected behavior**
Should return a list of countries

**Additional context**
1) In the country utils where you load all countries, you are accessing the city JSON instead of the one for country.
<img width="600" alt="Screenshot 2022-11-22 at 1 59 53 PM" src="https://user-images.githubusercontent.com/25941404/203321547-c1d1c43d-6fe8-43c3-8ddf-832c947fefa4.png">

2) The country JSON has a key `phonecode` in small letters, but the Country model is trying to parse from a key in camelCase `phoneCode`.
<img width="228" alt="Screenshot 2022-11-22 at 2 03 00 PM" src="https://user-images.githubusercontent.com/25941404/203321990-4984ff7e-3957-48d8-9886-47cac76d2f02.png">

<img width="525" alt="Screenshot 2022-11-22 at 2 03 42 PM" src="https://user-images.githubusercontent.com/25941404/203322029-1b5b1a77-b2ac-4e5b-ae62-041828f46f9d.png">

**Comment by toykam** [comment]
The issue is that the city.json file is been accessed instead of the country.json file. I will fix and send a pull request soon.

**Comment by paulpascal** [comment]
@j-mary 🙋‍♂️,
Sorry for the delay, 
Will check it and provide a fix quickly. 

Thanks

**Comment by paulpascal** [comment]
Would appreciate that @toykam 

Thanks
